# Generated by Django 6.0.4 on 2026-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_limit',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
