# Generated by Django 6.0.4 on 2026-05-15 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('match_type', models.CharField(choices=[('single', 'Single Player Matches'), ('team', 'Team Tournament')], max_length=20)),
                ('matches_per_pair', models.PositiveIntegerField(default=1)),
                ('match_days', models.PositiveIntegerField(default=1)),
                ('semifinal_qualifiers', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_competitions', to='auction.auction')),
                ('teams', models.ManyToManyField(blank=True, related_name='fixture_competitions', to='auction.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FixtureMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('league', 'League'), ('semi', 'Semi Final'), ('final', 'Final')], default='league', max_length=20)),
                ('match_day', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixture_matches', to='auction.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='auction.fixturecompetition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixture_matches', to='auction.team')),
            ],
            options={
                'ordering': ['stage', 'match_day', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FixtureLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.PositiveIntegerField(default=0)),
                ('away_goals', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('away_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_fixture_lineups', to='auction.player')),
                ('home_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_fixture_lineups', to='auction.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='auction.fixturematch')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
