# Generated by Django 6.0.4 on 2026-05-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_fixturecompetition_fixturematch_fixturelineup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixturematch',
            options={'ordering': ['match_day', 'order', 'id']},
        ),
    ]
