# Generated by Django 6.0.4 on 2026-05-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_fixturematch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FixtureRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='auction.fixturecompetition')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_roster_entries', to='auction.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_roster_entries', to='auction.team')),
            ],
            options={
                'ordering': ['team__name', 'name'],
                'unique_together': {('competition', 'team', 'name')},
            },
        ),
        migrations.AddField(
            model_name='fixturelineup',
            name='away_roster_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_fixture_lineups', to='auction.fixturerosterentry'),
        ),
        migrations.AddField(
            model_name='fixturelineup',
            name='home_roster_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_fixture_lineups', to='auction.fixturerosterentry'),
        ),
        migrations.AddField(
            model_name='fixturecompetition',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='auction.fixtureseason'),
        ),
    ]
