# Generated by Django 6.0.4 on 2026-05-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_fixtureseason_fixturerosterentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_color',
            field=models.CharField(default='#1F3322', max_length=7),
        ),
    ]
