# Generated by Django 6.0.4 on 2026-06-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_team_logo_team_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturecompetition',
            name='format_type',
            field=models.CharField(choices=[('ezone_custom', 'Ezone Custom (QF → SF → Final)'), ('top4_semi', 'Top 4 Semi Finals'), ('top2_final', 'Top 2 Direct Final'), ('knockout', 'Knockout Bracket'), ('group_stage', 'Group Stage')], default='ezone_custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='fixturematch',
            name='stage',
            field=models.CharField(choices=[('league', 'League'), ('quarter', 'Quarter Final'), ('semi', 'Semi Final'), ('final', 'Final')], default='league', max_length=20),
        ),
    ]
