# Generated by Django 6.0.4 on 2026-06-21 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_add_format_type_to_fixture_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturecompetition',
            name='completion_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixturecompetition',
            name='runner_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_up_fixture_competitions', to='auction.team'),
        ),
        migrations.AddField(
            model_name='fixturecompetition',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='fixturecompetition',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_fixture_competitions', to='auction.team'),
        ),
    ]
