# Generated by Django 6.0.4 on 2026-06-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_customtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtournament',
            name='champions_squad',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customtournament',
            name='runner_up_logo',
            field=models.ImageField(blank=True, null=True, upload_to='custom_tournaments/logos/'),
        ),
        migrations.AddField(
            model_name='customtournament',
            name='winner_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_tournaments/banners/'),
        ),
        migrations.AddField(
            model_name='customtournament',
            name='winner_description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtournament',
            name='winner_description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtournament',
            name='winner_quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
