# Generated by Django 6.0.4 on 2026-06-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_customtournament_champions_squad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixturecompetition',
            name='format_type',
            field=models.CharField(blank=True, default='League', max_length=100),
        ),
    ]
