# Generated by Django 6.0.4 on 2026-07-11 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_alter_fixturecompetition_format_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturecompetition',
            name='teams_per_group_advance',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='fixturematch',
            name='stage',
            field=models.CharField(choices=[('league', 'League'), ('round_of_32', 'Round of 32'), ('round_of_16', 'Round of 16'), ('quarter', 'Quarter Final'), ('semi', 'Semi Final'), ('final', 'Final')], default='league', max_length=20),
        ),
        migrations.CreateModel(
            name='FixtureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='auction.fixturecompetition')),
                ('teams', models.ManyToManyField(blank=True, related_name='fixture_groups', to='auction.team')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fixturematch',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='auction.fixturegroup'),
        ),
    ]
