# Generated by Django 6.0.4 on 2026-07-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_fixturecompetition_teams_per_group_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturecompetition',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
