# Generated by Django 6.0.4 on 2026-07-20 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_fixturecompetition_is_default'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturerosterentry',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_entries', to='players.playerprofile'),
        ),
    ]
