# Generated by Django 6.0.4 on 2026-07-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_fixturerosterentry_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='custom_bid_disabled',
            field=models.BooleanField(default=False, help_text='When on, captains can only use the quick-bid buttons — the free-type bid amount input is hidden.'),
        ),
        migrations.AddField(
            model_name='auction',
            name='price_decrement',
            field=models.PositiveIntegerField(default=5, help_text="Amount subtracted from a player's base price each time they go unsold/skipped."),
        ),
        migrations.AddField(
            model_name='auction',
            name='price_lock_enabled',
            field=models.BooleanField(default=False, help_text='When on, a team cannot bid more than what leaves enough balance to still afford its remaining required roster slots.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.CharField(choices=[('bigtime', 'Bigtime'), ('epic', 'Epic'), ('showtime', 'Showtime'), ('highlight', 'Highlight'), ('base', 'Base')], default='base', max_length=20),
        ),
    ]
