# Generated by Django 6.0.4 on 2026-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auction_custom_bid_disabled_auction_price_decrement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_fixture_only',
            field=models.BooleanField(default=False, help_text="Auto-created container for teams entered directly at fixture-creation time (no live auction ever runs). Hidden from the manager's auctions dashboard."),
        ),
    ]
