# Generated by Django 6.0.4 on 2026-07-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_auction_is_fixture_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturelineup',
            name='away_penalty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixturelineup',
            name='home_penalty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixturelineup',
            name='penalty_shootout',
            field=models.BooleanField(default=False, help_text='This player set finished level and was decided by a penalty shootout.'),
        ),
    ]
