# Generated by Django 6.0.4 on 2026-08-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_fixturelineup_away_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('ezone', 'eZone Auction'), ('live', 'Live Auction')], default='ezone', help_text='A Live Auction shows the uploaded participant card artwork instead of the stat-based player card.', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='card_image_url',
            field=models.URLField(blank=True, default='', help_text='Direct image URL for the participant card artwork, normalised on import.', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, default='', help_text='Playing position (CF, GK, CB...), shown on the Live Auction card.', max_length=10),
        ),
    ]
