# Generated by Django 6.0.4 on 2026-08-01 21:18

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_auction_auction_type_player_card_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='customtournament',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='fixturecompetition',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='fixturematch',
            options={'base_manager_name': 'all_objects', 'ordering': ['match_day', 'order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='fixturerosterentry',
            options={'base_manager_name': 'all_objects', 'ordering': ['team__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='fixtureseason',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='auction',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customtournament',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fixturecompetition',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fixturematch',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fixturerosterentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='fixtureseason',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='team',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the app but kept in the database. Untick to restore.'),
        ),
        migrations.AddField(
            model_name='customtournament',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtournament',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the app but kept in the database. Untick to restore.'),
        ),
        migrations.AddField(
            model_name='fixturecompetition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturecompetition',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the app but kept in the database. Untick to restore.'),
        ),
        migrations.AddField(
            model_name='fixturematch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturematch',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the app but kept in the database. Untick to restore.'),
        ),
        migrations.AddField(
            model_name='fixturerosterentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixturerosterentry',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the app but kept in the database. Untick to restore.'),
        ),
        migrations.AddField(
            model_name='fixtureseason',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixtureseason',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the app but kept in the database. Untick to restore.'),
        ),
        migrations.AddField(
            model_name='team',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the app but kept in the database. Untick to restore.'),
        ),
    ]
