# Generated by Django 6.0.4 on 2026-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_alter_auction_options_alter_customtournament_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionteam',
            name='max_players',
            field=models.PositiveIntegerField(blank=True, help_text="Overrides the auction's max players for this team only. Leave blank to use the auction default.", null=True),
        ),
    ]
