# Generated by Django 6.0.4 on 2026-08-05 15:04

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0020_auctionteam_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='quick_bid_increments',
            field=models.JSONField(default=auction.models.default_quick_bid_increments, help_text='Dollar amounts for the captain quick-bid buttons, e.g. [5, 10, 25, 50]. One button is rendered per value.'),
        ),
    ]
