# Generated by Django 6.0.4 on 2026-08-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_auction_quick_bid_increments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_public',
            field=models.BooleanField(default=False, help_text='When on, spectators can find and watch this auction on the public Live Auctions page. Off by default — the manager must opt in.'),
        ),
    ]
