# Generated by Django 6.0.4 on 2026-08-07 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0022_auction_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auctioneers',
            field=models.ManyToManyField(blank=True, help_text='Auctioneer accounts allowed to watch this auction and pause/resume the timer — no other controls.', limit_choices_to={'role': 'auctioneer'}, related_name='auctioneer_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='auto_advance_enabled',
            field=models.BooleanField(default=True, help_text='When on, the next player automatically loads onto the block once the current one is sold/unsold. When off, the manager must click Next Player manually.'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('captain', 'Captain'), ('auctioneer', 'Auctioneer')], default='captain', max_length=20),
        ),
    ]
