# Generated by Django 6.0.4 on 2026-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0023_auction_auctioneers_auction_auto_advance_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auto_count_enabled',
            field=models.BooleanField(default=False, help_text='When on, the 3-2-1 countdown starts automatically when the timer hits 0 with bids present. When off, the manager must click Count manually.'),
        ),
    ]
