# Generated by Django 6.0.4 on 2026-07-20 12:35

import players.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('efootball_id', models.CharField(max_length=100, unique=True)),
                ('instagram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(upload_to='player_photos/', validators=[players.validators.validate_photo_size])),
                ('rating', models.PositiveIntegerField(default=62)),
                ('is_verified', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
