# Generated by Django 6.0.4 on 2026-07-20 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_fixturerosterentry_profile'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('golden_ball', 'Golden Ball'), ('golden_glove', 'Golden Glove')], max_length=20)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_badges', to='auction.fixturecompetition')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='players.playerprofile')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('competition', 'badge_type')},
            },
        ),
    ]
