# Generated by Django 6.0.4 on 2026-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Centre Back'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('DMF', 'Defensive Midfielder'), ('CMF', 'Central Midfielder'), ('AMF', 'Attacking Midfielder'), ('RWF', 'Right Wing Forward'), ('LWF', 'Left Wing Forward'), ('SS', 'Second Striker'), ('CF', 'Centre Forward')], max_length=10, null=True),
        ),
    ]
