# Generated by Django 6.0.4 on 2026-07-20 19:29

import players.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_playerprofile_country_playerprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/', validators=[players.validators.validate_photo_size]),
        ),
    ]
