# Generated by Django 6.0.4 on 2026-08-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_playerprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
